### ISSUE TITLE
Watchdog No Display

### ISSUE THREAD

**Issue by rolywebb** [seandepagnier/watchdog_pi#133] opened 2023-12-28 21:33 UTC
Using:  Pi 4 64 bit OS; OpenPlotter 5.8.4; WatchDog 2.4.103

Watchdog appears to install OK using PIM.  Watchdog icon appears in OCPN toolbar.
Click on Watchdog icon gives a blank screen.  See attached screenshot.

Reinstalling has no effect.  So far I have not been able to install a legacy version.

Any help/advice would be most welcome

![Watchdog Screenshot](https://github.com/seandepagnier/watchdog_pi/assets/55076562/c26d2616-4d3f-4745-af5d-82e49317f53f)

**Comment by rolywebb** [comment] 2023-12-28 21:39
OOOPPSS!!!!

I just discovered that a right click on the blank screen brings up the selection drop down list for setting various alarms.

Silly me.

Sorry to waste your time

**Comment by seandepagnier** [comment] 2023-12-28 23:56
it is supposed to say that in the blank space if there are no alarms
not sure what happened.

**Comment by rgleason** [comment] 2024-01-08 14:54
This is not a bug really, but the initial screen should show a message when it is empty
`"Right click to configure a  "New" alarm."`

**Comment by rolywebb** [comment] 2024-01-08 21:08
Sean has already pointed out that the message you refer to SHOULD display.
However, it does not, as the screenshot attached to my report shows.  I
would have thought incorrect/misleading displays are bugs.
For newbies like me it took a lot of unnecessary floundering about to find
the solution.

**Comment by rgleason** [comment] 2024-01-10 18:08
I understand @rolywebb  Thanks for reporting. 
We are suggesting that a message be added.
"Hold down"(android) or "Right Click" select "New" alarm.

**Comment by rgleason** [comment] 2024-01-26 01:27
This is now on the list, in another location. See above.
Can you please close this now?  I cannot close it. Only you can close it. Thanks.

**Comment by rolywebb** [comment] 2024-01-26 05:58
Yes, will do.

**Comment by rgleason** [comment] 2024-01-26 12:57
@rolywebb  Will you please close this now? We have it listed elsewhere. This is a duplicate. You must hit the button at the bottom to close the Issue!!!!!!  Thanks.  (I can't close it)

**Closed** 2024-01-26 20:26 UTC

**Comment by rgleason** [comment] 2024-01-27 01:42
Thanks

**Comment by rgleason** [comment] 2024-01-27 01:43
Go ahead and test the new WD 2.4.105  not everything is fixed but it it better.

**Comment by rgleason** [comment] 2024-03-25 15:24
Read the manual. Please close this post.
